##
# Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: brundun
  labels:
    app: brundun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brundun
  template:
    metadata:
      labels:
        app: brundun
    spec:
      containers:
      - name: brundun
        image: docker.io/srclosson/brundun:latest
        ports:
        - containerPort: 8080

##
# Service
---
apiVersion: v1
kind: Service
metadata:
  name: brundun
  labels:
    app: brundun
spec:
  selector:
    app: brundun
  ports:
  - port: 80
    targetPort: 8080


